markdown: kramdown
permalink: /:title/
url: https://amgod.js.org
name: Amgod blog
author: Amgod
email: amgod20@qq.com
beian: None
weibo: 18850691
github: Amgod
safe: true
paginate: 20
about: "欢迎观赏、建议、拍砖……"
